# Generated by Django 2.1.4 on 2018-12-13 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estacionamento', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parametros',
            options={'verbose_name': 'Parametro', 'verbose_name_plural': 'Parametros'},
        ),
    ]
