# Generated by Django 2.1.4 on 2018-12-13 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_auto_20181212_1448'),
        ('apartamentos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.Juridica')),
            ],
        ),
        migrations.AddField(
            model_name='apartamentos',
            name='pertence',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='apartamentos.Hotel'),
            preserve_default=False,
        ),
    ]
