# Generated by Django 2.1.4 on 2018-12-13 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartamentos', '0003_auto_20181213_1449'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apartamentos',
            options={'verbose_name': 'Apartamento', 'verbose_name_plural': 'Apartamentos'},
        ),
    ]
