# Generated by Django 2.1.4 on 2018-12-13 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_auto_20181213_1250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='name',
        ),
        migrations.DeleteModel(
            name='Hotel',
        ),
    ]
