# Generated by Django 2.1.4 on 2018-12-13 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0004_auto_20181213_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='valor_pago',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
